Repository addadileonardo/AddaDiLeonardo, pull requests merged in 2020-01, with the labels that each got.

#1 Aggiornamento progetto
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/NavigationPage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/NavigationPage.xaml.cs
Labels: enhancement

#2 Inizio HomePage
  AddaDiLeonardo/AddaDiLeonardo.Android/Resources/Resource.designer.cs
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/App.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Images/backgroundFadeBlack.png
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/NavPage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/NavPage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/NavigationPage.xaml.cs
Labels: enhancement

#4 Gestione click tappe
  AddaDiLeonardo/AddaDiLeonardo.Android/Resources/Resource.designer.cs
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/Images/Icons/home.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Icons/map.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Icons/settings.png
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/NavPage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPage.xaml.cs
Labels: enhancement

#5 Accordion
  AddaDiLeonardo/AddaDiLeonardo.Android/AddaDiLeonardo.Android.csproj
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPage.xaml
Labels: enhancement

#44 Backend
  AddaDiLeonardo/AddaDiLeonardo.Android/MainActivity.cs
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/App.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/PlayerPage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/PlayerPage.xaml.cs
Labels: New features

#50 Accordion, Tappa, Services, Assets
  AddaDiLeonardo/AddaDiLeonardo.Android/AddaDiLeonardo.Android.csproj
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Ponte.jpg
  AddaDiLeonardo/AddaDiLeonardo.Android/BaseUrl_Android.cs
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml
  AddaDiLeonardo/AddaDiLeonardo/Files/Ponte/Ponte_Intro.html
  AddaDiLeonardo/AddaDiLeonardo/Files/Ponte/Ponte_section_1.html
  AddaDiLeonardo/AddaDiLeonardo/Services/HtmlServices.cs
  AddaDiLeonardo/AddaDiLeonardo/Services/IBaseUrl.cs
  AddaDiLeonardo/AddaDiLeonardo/Services/IHtmlServices.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml.cs
Labels: New features

#54 Accordion, Eliminati i file non necessari, Google Fonts (android)
  AddaDiLeonardo/AddaDiLeonardo.Android/AddaDiLeonardo.Android.csproj
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Oswald-Light.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Oswald-Regular.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Ponte/Ponte.jpg
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml
  AddaDiLeonardo/AddaDiLeonardo/Files/BaseTappa/BaseHtml.html
  AddaDiLeonardo/AddaDiLeonardo/Files/Ponte/Ponte_Intro.html
  AddaDiLeonardo/AddaDiLeonardo/Files/Ponte/Ponte_section_1.html
  AddaDiLeonardo/AddaDiLeonardo/Images/Ponte/Ponte.jpg
  AddaDiLeonardo/AddaDiLeonardo/Views/BaseTappa.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/BaseTappa.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml.cs
Labels: New features

#65 Tappa ponte, Html, Font (Android)
  AddaDiLeonardo/AddaDiLeonardo.Android/AddaDiLeonardo.Android.csproj
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Icons/marker.png
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Roboto-Light.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Roboto-Regular.ttf
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml
  AddaDiLeonardo/AddaDiLeonardo/Files/Ponte/Ponte_Intro.html
  AddaDiLeonardo/AddaDiLeonardo/Files/Ponte/Ponte_section_1.html
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml.cs
Labels: Android

#68 Sincronizzazione
  AddaDiLeonardo/AddaDiLeonardo.Android/AddaDiLeonardo.Android.csproj
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Icons/marker.png
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Oswald-Light.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Oswald-Regular.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Ponte/Ponte.jpg
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Roboto-Light.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Roboto-Regular.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/BaseUrl_Android.cs
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml
  AddaDiLeonardo/AddaDiLeonardo/Files/BaseTappa/BaseHtml.html
  AddaDiLeonardo/AddaDiLeonardo/Files/Ponte/Ponte_Intro.html
  AddaDiLeonardo/AddaDiLeonardo/Files/Ponte/Ponte_section_1.html
  AddaDiLeonardo/AddaDiLeonardo/Images/Map/MappaRaul.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Map/rectanglePosition.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Ponte/Ponte.jpg
  AddaDiLeonardo/AddaDiLeonardo/Services/HtmlServices.cs
  AddaDiLeonardo/AddaDiLeonardo/Services/IBaseUrl.cs
  AddaDiLeonardo/AddaDiLeonardo/Services/IHtmlServices.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/BaseTappa.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/BaseTappa.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/Map.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/Map.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml.cs
  README.md
Labels: Sync

#77 Custom Label
  AddaDiLeonardo/AddaDiLeonardo.Android/AddaDiLeonardo.Android.csproj
  AddaDiLeonardo/AddaDiLeonardo.Android/CustomLabelRender.cs
  AddaDiLeonardo/AddaDiLeonardo.iOS/AddaDiLeonardo.iOS.csproj
  AddaDiLeonardo/AddaDiLeonardo.iOS/CustomLabelRender.cs
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml
  AddaDiLeonardo/AddaDiLeonardo/CustomLabel.cs
  AddaDiLeonardo/AddaDiLeonardo/Files/Ponte/Ponte_section_1.html
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml.cs
Labels: New features

#79 Sincronizzazione
  AddaDiLeonardo/AddaDiLeonardo.Android/AddaDiLeonardo.Android.csproj
  AddaDiLeonardo/AddaDiLeonardo.Android/CustomLabelRender.cs
  AddaDiLeonardo/AddaDiLeonardo.iOS/AddaDiLeonardo.iOS.csproj
  AddaDiLeonardo/AddaDiLeonardo.iOS/CustomLabelRender.cs
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml
  AddaDiLeonardo/AddaDiLeonardo/CustomLabel.cs
  AddaDiLeonardo/AddaDiLeonardo/Files/Ponte/Ponte_section_1.html
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml.cs
Labels: Sync

#83 Sincronizzazione
  AddaDiLeonardo/AddaDiLeonardo.Android/AddaDiLeonardo.Android.csproj
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Oswald-Bold.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Oswald-SemiBold.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Roboto-Italic.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Roboto-LightItalic.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Roboto-ThinItalic.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/CustomLabelRender.cs
  AddaDiLeonardo/AddaDiLeonardo.iOS/AddaDiLeonardo.iOS.csproj
  AddaDiLeonardo/AddaDiLeonardo.iOS/CustomLabelRender.cs
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml
  AddaDiLeonardo/AddaDiLeonardo/CustomLabel.cs
  AddaDiLeonardo/AddaDiLeonardo/Files/Ponte/Ponte_Intro.html
  AddaDiLeonardo/AddaDiLeonardo/Files/Ponte/Ponte_section_1.html
  AddaDiLeonardo/AddaDiLeonardo/Images/Icons/marker.png
  AddaDiLeonardo/AddaDiLeonardo/Images/marker.png
  AddaDiLeonardo/AddaDiLeonardo/MarkupExtension/EmbeddedImage.cs
  AddaDiLeonardo/AddaDiLeonardo/Services/HtmlServices.cs
  AddaDiLeonardo/AddaDiLeonardo/Services/IHtmlServices.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/Map.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/Map.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/NavPage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/NavPage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml.cs
  README.md
Labels: Sync

#89 Sincronizzazione
  AddaDiLeonardo/AddaDiLeonardo.Android/AddaDiLeonardo.Android.csproj
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Oswald-Bold.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Oswald-SemiBold.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Roboto-Italic.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Roboto-LightItalic.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Roboto-ThinItalic.ttf
  AddaDiLeonardo/AddaDiLeonardo.iOS/AddaDiLeonardo.iOS.csproj
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Oswald-Bold.ttf
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Oswald-Light.ttf
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Oswald-Regular.ttf
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Oswald-SemiBold.ttf
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Roboto-Italic.ttf
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Roboto-Light.ttf
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Roboto-LightItalic.ttf
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Roboto-Regular.ttf
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Roboto-ThinItalic.ttf
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/Files/Ponte/Ponte_Intro.html
  AddaDiLeonardo/AddaDiLeonardo/Files/Ponte/Ponte_section_1.html
  AddaDiLeonardo/AddaDiLeonardo/Images/Icons/marker.png
  AddaDiLeonardo/AddaDiLeonardo/Images/marker.png
  AddaDiLeonardo/AddaDiLeonardo/Services/HtmlServices.cs
  AddaDiLeonardo/AddaDiLeonardo/Services/IHtmlServices.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml.cs
  README.md
Labels: Sync

#99 Sincronizzazione
  AddaDiLeonardo/AddaDiLeonardo.Android/MainActivity.cs
  AddaDiLeonardo/AddaDiLeonardo.iOS/AppDelegate.cs
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/Images/Centrali/Centrale_Bertini.jpg
  AddaDiLeonardo/AddaDiLeonardo/Images/Rocchetta/Rocchetta.jpg
  AddaDiLeonardo/AddaDiLeonardo/Images/Traghetto/Traghetto.jpg
  AddaDiLeonardo/AddaDiLeonardo/Views/PlayerPage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaCentrali.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaCentrali.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaRocchetta.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaRocchetta.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaTraghetto.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaTraghetto.xaml.cs
Labels: Sync

#102 Player YouTube video
  AddaDiLeonardo/AddaDiLeonardo.Android/MainActivity.cs
  AddaDiLeonardo/AddaDiLeonardo.iOS/Main.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/PlayerPage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/PlayerPage.xaml.cs
Labels: Sync

#107 Sincronizzazione
  AddaDiLeonardo/AddaDiLeonardo.Android/MainActivity.cs
  AddaDiLeonardo/AddaDiLeonardo.iOS/Main.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/PlayerPage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/PlayerPage.xaml.cs
  README.md
Labels: Sync

#109 Seleziona lingua dalle impostazioni
  AddaDiLeonardo/AddaDiLeonardo.iOS/Info.plist
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/App.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Images/Bella.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Prova3.png
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/Map.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/Settings.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/Settings.xaml.cs
Labels: Impostazioni, New features, iOS

#113 Sincronizzazione Backend
  AddaDiLeonardo/AddaDiLeonardo.Android/AddaDiLeonardo.Android.csproj
  AddaDiLeonardo/AddaDiLeonardo.Android/VideoPlayerRender.cs
  AddaDiLeonardo/AddaDiLeonardo/VideoPlayer.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/PlayerPage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/PlayerPage.xaml.cs
Labels: Sync

#116 Sincronizzazione
  AddaDiLeonardo/AddaDiLeonardo.Android/AddaDiLeonardo.Android.csproj
  AddaDiLeonardo/AddaDiLeonardo.Android/Resources/Resource.designer.cs
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/VideoPlayer.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/PlayerPage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/PlayerPage.xaml.cs
Labels: Sync

#121 Sincronizzazione
  AddaDiLeonardo/AddaDiLeonardo.Android/AddaDiLeonardo.Android.csproj
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/FontAwesome5Brands.otf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/FontAwesome5Regular.otf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/FontAwesome5Solid.otf
  AddaDiLeonardo/AddaDiLeonardo.Android/MainActivity.cs
  AddaDiLeonardo/AddaDiLeonardo.Android/Resources/Resource.designer.cs
  AddaDiLeonardo/AddaDiLeonardo.iOS/AddaDiLeonardo.iOS.csproj
  AddaDiLeonardo/AddaDiLeonardo.iOS/AppDelegate.cs
  AddaDiLeonardo/AddaDiLeonardo.iOS/Info.plist
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/FontAwesome5Brands.otf
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/FontAwesome5Regular.otf
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/FontAwesome5Solid.otf
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/NavPage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/PlayerPage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/PlayerPage.xaml.cs
Labels: Sync

#123 Backend
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/App.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/Classes/Contenuto.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/Classes/Sezione.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/Classes/Tappa.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/DatabaseConstants.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/LanguageDatabase.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/Struttura.txt
  AddaDiLeonardo/AddaDiLeonardo/Database/TaskExtensions.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml.cs
Labels: Sync

#124 Sincronizzazione
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/App.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/Classes/Contenuto.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/Classes/Sezione.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/Classes/Tappa.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/DatabaseConstants.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/LanguageDatabase.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/Struttura.txt
  AddaDiLeonardo/AddaDiLeonardo/Database/TaskExtensions.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml.cs
Labels: Sync

#129 Backend Database
  AddaDiLeonardo.sln
  AddaDiLeonardo/AddaDiLeonardo.Android/AddaDiLeonardo.Android.csproj
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Italian.db3
  AddaDiLeonardo/AddaDiLeonardo.Android/DatabaseService.cs
  AddaDiLeonardo/AddaDiLeonardo.iOS/AddaDiLeonardo.iOS.csproj
  AddaDiLeonardo/AddaDiLeonardo.iOS/DatabaseService.cs
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Italian.db3
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/App.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/Classes/Contenuto.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/IDBInterface.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/LanguageDatabase.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml.cs
  Database/Italian.db3
Labels: Android, Tappa, area-database

#136 Allineamento
  AddaDiLeonardo.sln
  AddaDiLeonardo/AddaDiLeonardo.Android/AddaDiLeonardo.Android.csproj
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Italian.db3
  AddaDiLeonardo/AddaDiLeonardo.Android/DatabaseService.cs
  AddaDiLeonardo/AddaDiLeonardo.Android/Properties/AndroidManifest.xml
  AddaDiLeonardo/AddaDiLeonardo.Android/Properties/AssemblyInfo.cs
  AddaDiLeonardo/AddaDiLeonardo.iOS/AddaDiLeonardo.iOS.csproj
  AddaDiLeonardo/AddaDiLeonardo.iOS/DatabaseService.cs
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Italian.db3
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/App.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/Classes/Contenuto.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/IDBInterface.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/LanguageDatabase.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/PlayerPage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/PlayerPage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml.cs
  Database/Italian.db3
Labels: Sync
