Repository addadileonardo/AddaDiLeonardo, pull requests merged in 2020-02, with the labels that each got.

#142 Sincronizzazione Backend e metodi Async
  AddaDiLeonardo/AddaDiLeonardo.Android/AddaDiLeonardo.Android.csproj
  AddaDiLeonardo/AddaDiLeonardo.iOS/AddaDiLeonardo.iOS.csproj
  AddaDiLeonardo/AddaDiLeonardo/Database/LanguageDatabase.cs
Labels: Sync

#143 Database
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Italian.db3
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Italian.db3
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaRocchetta.xaml.cs
  Database/Italian.db3
Labels: Sync

#146 Allinemento
  AddaDiLeonardo/AddaDiLeonardo.Android/AddaDiLeonardo.Android.csproj
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Italian.db3
  AddaDiLeonardo/AddaDiLeonardo.iOS/AddaDiLeonardo.iOS.csproj
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Italian.db3
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/LanguageDatabase.cs
  AddaDiLeonardo/AddaDiLeonardo/Images/Icons/pin.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Rocchetta/IMG_9730.JPG
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaPonte.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaRocchetta.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaRocchetta.xaml.cs
  Database/Italian.db3
Labels: Sync

#160 Spaziatura Homepage
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml
Labels: Frontend-only, Homepage

#164 Allineamento
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml
  README.md
Labels: Sync

#167 Backend
  AddaDiLeonardo/AddaDiLeonardo.Android/AddaDiLeonardo.Android.csproj
  AddaDiLeonardo/AddaDiLeonardo/Views/PlayerPage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/PlayerPage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaRocchetta.xaml.cs
Labels: Sync

#171 Allineamento
  AddaDiLeonardo/AddaDiLeonardo.Android/AddaDiLeonardo.Android.csproj
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Roboto-Bold.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Roboto-BoldItalic.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Roboto-Medium.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Roboto-MediumItalic.ttf
  AddaDiLeonardo/AddaDiLeonardo.iOS/AddaDiLeonardo.iOS.csproj
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Roboto-Bold.ttf
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Roboto-BoldItalic.ttf
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Roboto-Medium.ttf
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Roboto-MediumItalic.ttf
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/Content/testgif.gif
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/CustomLabelTitle.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/LanguageDatabase.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/PlayerPage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/PlayerPage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaRocchetta.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaRocchetta.xaml.cs
Labels: Sync

#174 Allineamento
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml.cs
Labels: Sync

#180 Allineamento
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaRocchetta.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaRocchetta.xaml.cs
Labels: Sync

#182 Allineamento
  AddaDiLeonardo/AddaDiLeonardo.Android/AddaDiLeonardo.Android.csproj
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Ponte/Ponte.jpg
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/RobotoCondensed-Bold.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/RobotoCondensed-BoldItalic.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/RobotoCondensed-Italic.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/RobotoCondensed-Light.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/RobotoCondensed-LightItalic.ttf
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/RobotoCondensed-Regular.ttf
  AddaDiLeonardo/AddaDiLeonardo.iOS/AddaDiLeonardo.iOS.csproj
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/RobotoCondensed-Bold.ttf
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/RobotoCondensed-BoldItalic.ttf
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/RobotoCondensed-Italic.ttf
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/RobotoCondensed-Light.ttf
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/RobotoCondensed-LightItalic.ttf
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/RobotoCondensed-Regular.ttf
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Images/Icons/Icon-Place.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Icons/Icon-Place_@2x.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Icons/Icon-Place_@3x.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Icons/Icon-Place_@4x.png
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaRocchetta.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaRocchetta.xaml.cs
Labels: Sync

#185 Restyling Homepage
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/Images/Home/new/backgroundtesto.jpg
  AddaDiLeonardo/AddaDiLeonardo/Images/Home/new/centrale.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Home/new/play.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Home/new/ponte.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Home/new/rocchetta.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Home/new/traghetto.png
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml
Labels: Homepage

#187 Allineamento
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/Images/Home/new/backgroundtesto.jpg
  AddaDiLeonardo/AddaDiLeonardo/Images/Home/new/centrale.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Home/new/play.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Home/new/ponte.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Home/new/rocchetta.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Home/new/traghetto.png
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml
Labels: Sync

#191 Allineamento
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/Images/Icons/close.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Icons/close/arrow.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Icons/close/back.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Icons/close/close_1.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Icons/close/close_2.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Icons/close/close_3.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Icons/close/close_4.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Icons/close/close_5.png
  AddaDiLeonardo/AddaDiLeonardo/Images/Icons/close_1.png
  AddaDiLeonardo/AddaDiLeonardo/Views/NavPage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaRocchetta.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/TappaRocchetta.xaml.cs
Labels: Sync

#193 Test Homepage
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml
Labels: Test
