Repository addadileonardo/AddaDiLeonardo, pull requests merged in 2020-06, with the labels that each got.

#153 Sync
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/App.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/Accordion.xaml
  AddaDiLeonardo/AddaDiLeonardo/Images/Tappe/cover/rocchetta2_cover.jpg
  AddaDiLeonardo/AddaDiLeonardo/Images/Tappe/cover/rocchetta_cover_v2.png
  AddaDiLeonardo/AddaDiLeonardo/Views/Blank.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/Blank.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/Tappe/Tappa_03.xaml.cs
Labels: sync

#155 Modifica Database: contenuti e tabella errori
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Francese.db
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Inglese.db
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Italiano.db
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Francese.db
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Inglese.db
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Italiano.db
  AddaDiLeonardo/AddaDiLeonardo/Database/Data/Errori.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/Database.cs
Labels: Crediti, Database, Homepage, enhancement

#156 sync
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Francese.db
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Inglese.db
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Italiano.db
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Francese.db
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Inglese.db
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Italiano.db
  AddaDiLeonardo/AddaDiLeonardo/Database/Data/Errori.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/Database.cs
Labels: sync

#159 Sync
  AddaDiLeonardo/AddaDiLeonardo.Android/AddaDiLeonardo.Android.csproj
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Francese.db
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Inglese.db
  AddaDiLeonardo/AddaDiLeonardo.Android/Assets/Italiano.db
  AddaDiLeonardo/AddaDiLeonardo.Android/CustomImageRender.cs
  AddaDiLeonardo/AddaDiLeonardo.iOS/AddaDiLeonardo.iOS.csproj
  AddaDiLeonardo/AddaDiLeonardo.iOS/CustomImageRender.cs
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Francese.db
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Inglese.db
  AddaDiLeonardo/AddaDiLeonardo.iOS/Resources/Italiano.db
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
  AddaDiLeonardo/AddaDiLeonardo/CustomControls/CustomImage.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/Data/Errori.cs
  AddaDiLeonardo/AddaDiLeonardo/Database/Database.cs
  AddaDiLeonardo/AddaDiLeonardo/Images/Home/Credits-Loghi.png
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/PlayerPage.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/Tappe/Tappa_03.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/Tappe/Tappa_04.xaml.cs
  AddaDiLeonardo/AddaDiLeonardo/Views/Tappe/Tappa_05.xaml.cs
Labels: sync

#161 Intro mappa e credits
  AddaDiLeonardo/AddaDiLeonardo/Images/Home/background.png
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml
  AddaDiLeonardo/AddaDiLeonardo/Views/HomePage.xaml.cs
Labels: Homepage, Mappa

#162 Eliminata image non utilizzata
  AddaDiLeonardo/AddaDiLeonardo/AddaDiLeonardo.csproj
Labels: Homepage
